---
- hosts: all
  remote_user: root
  vars:
    # project
    domain:    "example.varhoo.cz"
    proj:      "proj"
    http_port: "8000"
    db:        "postgresql"
    # email:    "root@localhost"

    # configuration on host
    user:         "{{ proj }}"
    home:         "/var/www/{{ proj }}"
    # configuration  docker guest
    docker_home:  "/app/{{ proj }}"
    # don't change
    image:        "{{proj}}.docker"

  roles:
    - common
    - webservice
